print("Welcome to the tip calculator.")
totalbill=float(input("What was the total bill?\n$"))
tip=int(input("What percentage tip would you like to give? 10,12, or 15?\n"))
people=int(input("How many people to split the bill?\n"))
bill=round((totalbill*(1+(tip/100)))/people,2)
print(f'Each person should pay: ${bill}')